CREATE TABLE prueba(cc VARCHAR (20) NOT NULL,nombre VARCHAR(20) NOT NULL)
CREATE TABLE prueba1(cc VARCHAR (20) NOT NULL,nombre VARCHAR(20) NOT NULL)
CREATE TABLE prueba2(cc VARCHAR (20) NOT NULL,nombre VARCHAR(20) NOT NULL)
CREATE TABLE prueba3(cc VARCHAR (20) NOT NULL,nombre VARCHAR(20) NOT NULL)